### ISSUE TITLE
ffobench crashes with file not found error

### ISSUE THREAD

**Issue by lk16** [primenumber/issen-rs#1]
Hi,

I am trying to play around with your project, but I ran into some issues.

This is what I did:
* I cloned your repo
* I downloaded the evaluation table data into the repo root 
* I ran `RUST_BACKTRACE=full cargo +nightly run --release -- ffobench`

I got this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/eval.rs:32:74
```

This seems to fail because I don't have the `config.yaml`.
Am I missing some steps or is this yaml file missing from the downloaded tar.gz file?

**Comment by primenumber** [comment]
Oh, yes.
I updated the archive: `table210925.tar.gz`

**Comment by lk16** [comment]
Thanks, I got it to work now.
